name: Build and Deploy Java API

on:
  push:
    branches:
      - main  # or any branch you want to trigger the workflow on
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Build with Maven
        run: |
          # Stop existing service (if any)
          # sudo systemctl stop arrancar-api.service || true
          cp /home/ubuntu/back/application.properties ./src/main/resources/application.properties
          mvn clean install
          # Copy the new jar to the deployment directory
          cp target/arrancar-api.jar /home/ubuntu/backend-api/
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Deploy application
        run: |
          # Stop existing service (if any)
          sudo systemctl stop arrancar-api.service || true

          # Start the service
          sudo systemctl start arrancar-api.service
